#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 13 12:46:41 2022

@author: aouyed
"""

import radiosonde_plotter as rp 
import pandas as pd
from parameters import parameters 

def main():
    param=parameters()
    df=pd.read_pickle('../data/processed/dataframes/'+param.month_string+'_winds_rs_model_'+param.tag+'.pkl')
    df=rp.preprocess(df)
    breakpoint()
    
    



if __name__=='__main__':
    main()